<a href="https://colab.research.google.com/github/ADARSH1115/ML-LAB/blob/main/ML_ASN2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, KBinsDiscretizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import jaccard_score, pairwise_distances
from scipy.spatial.distance import cosine
import os

In [ ]:
import pandas as pd

df=pd.DataFrame()
df['name']=['adarsh','bunty','AGRANIXOX','RDJ']
df['age']=['22','21',22,1880]
df.iloc[1:4]

        name   age
1      bunty    21
2  AGRANIXOX    22
3        RDJ  1880

In [ ]:
import pandas as pd

df=pd.DataFrame()
df['name']=['adarsh','bunty','AGRANIXOX','RDJ']
df['age']=['22','21',22,18]
df['gender']=['male','male','female','male']


df[df['gender']=='female']
df.iloc[:]

        name age  gender
0     adarsh  22    male
1      bunty  21    male
2  AGRANIXOX  22  female
3        RDJ  18    male

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('AWCustomers.csv')
df

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,NaN,Grace,C,Bailey,NaN,6627 Camelback Ct.,NaN,Coronado,California,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,2017-03-06
18357,11459,NaN,Tasha,NaN,Deng,NaN,9627 Kendall Rd,NaN,Port Macquarie,New South Wales,...,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,2017-03-06
18358,12160,NaN,Jaclyn,NaN,Zhang,NaN,4364 Viera Avenue,NaN,Beaverton,Oregon,...,Partial College,Skilled Manual,F,S,0,2,0,0,51859,2017-03-06
18359,14353,NaN,Erin,I,Reed,NaN,3866 Mt. Everest Court,NaN,Vancouver,British Columbia,...,High School,Clerical,F,S,0,0,0,0,87177,2017-03-06
18360,16676,NaN,Amanda,NaN,Perry,NaN,7870 Orangewood Dr.,NaN,Grossmont,California,...,Graduate Degree,Professional,F,M,1,2,0,0,136856,2017-03-06

Warning: Total number of columns (24) exceeds max_columns (20) limiting to first (20) columns.
Warning: Total number of columns (24) exceeds max_columns (20) limiting to first (20) columns.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
df=pd.read_csv('AWSales.csv')
df

       CustomerID  BikeBuyer  AvgMonthSpend
0           21173          1          50.97
1           13249          1          53.11
2           29350          1          54.08
3           13503          1          56.93
4           22803          1          55.41
...           ...        ...            ...
18350       25414          0          48.14
18351       11459          1          50.23
18352       12160          1          49.56
18353       14353          0          51.42
18354       16676          1          52.27

[18355 rows x 3 columns]

In [ ]:
df.columns

Index(['CustomerID', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix',
       'AddressLine1', 'AddressLine2', 'City', 'StateProvinceName',
       'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate',
       'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome', 'LastUpdated'],
      dtype='object')

In [ ]:
df.drop(['Title','Suffix','Education','MaritalStatus','Occupation','Gender','PhoneNumber','MiddleName'],axis=1,inplace=True)

KeyError: "['Title', 'Suffix', 'Education', 'MaritalStatus', 'Occupation', 'Gender', 'PhoneNumber', 'MiddleName'] not found in axis"

In [ ]:
df.columns

Index(['CustomerID', 'BikeBuyer', 'AvgMonthSpend'], dtype='object')

In [ ]:
df.drop(['AddressLine2'],axis=1,inplace=True)

KeyError: "['AddressLine2'] not found in axis"

In [ ]:
df.drop(['Suffix'],axis=1,inplace=True)

KeyError: "['Suffix'] not found in axis"

In [ ]:
df.drop(['Title'],axis=1,inplace=True)

In [ ]:
df.drop(['MiddleName'],axis=1,inplace=True)

In [ ]:
df.describe()

,CustomerID,BirthDate,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
count,18361.000000,18361,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18361
mean,20241.987092,1982-01-25 04:14:15.639671040,0.610588,1.270301,0.338162,0.850389,72754.779642,2017-03-06 00:05:29.393824256
min,11000.000000,1930-08-13 00:00:00,0.000000,0.000000,0.000000,0.000000,25435.000000,2017-03-06 00:00:00
25%,15621.000000,1974-09-08 00:00:00,0.000000,1.000000,0.000000,0.000000,53312.000000,2017-03-06 00:00:00
50%,20248.000000,1983-08-13 00:00:00,1.000000,1.000000,0.000000,0.000000,61851.000000,2017-03-06 00:00:00
75%,24863.000000,1990-09-23 00:00:00,1.000000,2.000000,1.000000,2.000000,87410.000000,2017-03-06 00:00:00
max,29483.000000,2000-12-26 00:00:00,1.000000,5.000000,3.000000,3.000000,139115.000000,2017-03-07 00:00:00
std,5336.332731,NaN,0.487630,0.913989,0.568957,0.927315,30686.014313,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18361 entries, 0 to 18360
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CustomerID            18361 non-null  int64
 1   Title                 101 non-null    object
 2   FirstName             18361 non-null  object
 3   MiddleName            10572 non-null  object
 4   LastName              18361 non-null  object
 5   Suffix                3 non-null      object
 6   AddressLine1          18361 non-null  object
 7   City                  18361 non-null  object
 8   StateProvinceName     18361 non-null  object
 9   CountryRegionName     18361 non-null  object
 10  PostalCode            18361 non-null  object
 11  PhoneNumber           18361 non-null  object
 12  BirthDate             18361 non-null  object
 13  Education             18361 non-null  object
 14  Occupation            18361 non-null  object
 15  Gender                18361 non-null  object
 16  MaritalStatus         18361 non-null  object
 17  HomeOwnerFlag         18361 non-null  int64
 18  NumberCarsOwned       18361 non-null  int64
 19  NumberChildrenAtHome  18361 non-null  int64
 20  TotalChildren         18361 non-null  int64
 21  YearlyIncome          18361 non-null  int64
 22  LastUpdated           18361 non-null  object
dtypes: int64(6), object(17)
memory usage: 3.2+ MB

In [ ]:
df.isnull().sum()

CustomerID              0
FirstName               0
LastName                0
AddressLine1            0
City                    0
StateProvinceName       0
CountryRegionName       0
PostalCode              0
PhoneNumber             0
BirthDate               0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
LastUpdated             0
dtype: int64

In [ ]:
df=df.astype({'BirthDate': 'datetime64[ns]'},copy=False)
df=df.astype({'LastUpdated': 'datetime64[ns]'},copy=False)

In [ ]:
print(df.columns)

Index(['CustomerID', 'FirstName', 'LastName', 'AddressLine1', 'City',
       'StateProvinceName', 'CountryRegionName', 'PostalCode', 'BirthDate',
       'HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome',
       'TotalChildren', 'YearlyIncome', 'LastUpdated'],
      dtype='object')

In [ ]:
len(df['YearlyIncome'].value_counts().index)

15356

In [ ]:
import pandas as pd
df=pd.read_csv('AWCustomers.csv')
df.columns

var_cat=[]
var_num=[]
for c in df.columns:
    if df[c].dtype=='float64':
        var_cat.append(c)
    if df[c].dtype=='int64':
         var_num.append(c)

print("Discrete Variables: ",var_num)
print("Continuous variables: ",var_cat)

Discrete Variables:  ['CustomerID', 'HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome']
Continuous variables:  []

In [ ]:
Nominal = [
    'CustomerID',
    'FirstName',
    'LastName',
    'AddressLine1',
    'City',
    'StateProvinceName',
    'CountryRegionName',
    'PostalCode',
    'Gender',
    'MaritalStatus',
    'HomeOwnerFlag',
    'BikeBuyer'
]
Ordinal=[]
Ratio = [
    'NumberCarsOwned',
    'NumberChildrenAtHome',
    'TotalChildren',
    'YearlyIncome',
    'AvgMonthSpend',
]
Interval=['BirthDate']
print("Nominal: ",Nominal)
print("Ordinal: ",Ordinal)
print("Ratio: ",Ratio)
print("Interval: ",Interval)

Nominal:  ['CustomerID', 'FirstName', 'LastName', 'AddressLine1', 'City', 'StateProvinceName', 'CountryRegionName', 'PostalCode', 'Gender', 'MaritalStatus', 'HomeOwnerFlag', 'BikeBuyer']
Ordinal:  []
Ratio:  ['NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren', 'YearlyIncome', 'AvgMonthSpend']
Interval:  ['BirthDate']

II part:

(a)Handling NUlls

In [ ]:
df.isnull().sum()

CustomerID              0
FirstName               0
LastName                0
AddressLine1            0
City                    0
StateProvinceName       0
CountryRegionName       0
PostalCode              0
PhoneNumber             0
BirthDate               0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
LastUpdated             0
dtype: int64

(b)Normalisation

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, KBinsDiscretizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import jaccard_score, pairwise_distances
from scipy.spatial.distance import cosine

scaler=MinMaxScaler()

df['AvgMonthSpend_Normalised']=scaler.fit_transform(df['AvgMonthSpend'].values.reshape(-1,1))
df['YearlyIncome_Normalised']=scaler.fit_transform(df['YearlyIncome'].values.reshape(-1,1))

KeyError: 'YearlyIncome'